packages:
  - .
  - vendor/*
  - vendor/Lacuna/analyzers/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - lmdb
  - msgpackr-extract
  - phantomjs-prebuilt-that-works
  - puppeteer
  - v8-profiler-next
