packages:
  - .
  - vendor/*
  - vendor/Lacuna/analyzers/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - lmdb
  - msgpackr-extract
  - puppeteer
  - v8-profiler-next

overrides:
  esprima-ast-utils: 0.0.7
