packages:
  - .
  - vendor/*
  - vendor/Lacuna/analyzers/*
  - src/packages/*
  - src/packages/napi/npm/*
  - src/tasks/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - esbuild
  - lmdb
  - msgpackr-extract
  - msw
  - puppeteer
  - unrs-resolver
  - v8-profiler-next
  - websocket

overrides:
  esprima-ast-utils: 0.0.7

supportedArchitectures:
  cpu: [current, wasm32]
